CREATE TABLE Pets (
    PetID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50),
    Breed VARCHAR(50),
    Age INT,
    Gender VARCHAR(10),
    Status VARCHAR(20),
    DateAdded TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(100),
    Email VARCHAR(100) UNIQUE,
    PasswordHash VARCHAR(255),
    Role VARCHAR(20) DEFAULT 'User',
    DateJoined TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
